import { BsStars } from "react-icons/bs";

const AiOverview = () => {
  return (
    <div className="space-y-6">
      <div className="flex-ic gap-3">
        <div className="size-10 flex-center bg-[url('/assets/static/ai-bg.svg')] bg-cover bg-center rounded-xl text-white animate-pulse text-xl">
          <BsStars />
        </div>
        <div>
          <p className="text-base font-bold">Summary of Buyers' Reviews</p>
          <p className="text-xs text-slate-500">
         Generated by AI
          </p>
        </div>
      </div>
      <div className="p-6 bg-[#F5F6FF] rounded-lg text-slate-800 font-medium text-[15px] leading-7 line-clamp-3">
     The SabzChinese SabzPod Bluetooth headphones, with their lightweight and comfortable design, are particularly suitable for calls and use in noisy environments. Users can easily use them while driving or exercising and have expressed satisfaction with being able to hear surrounding sounds. The call quality is generally good, and some users have also highlighted the long battery life.

      </div>
    </div>
  );
};

export default AiOverview;
